services:
  walrus:
    image: sealio/walrus:main
    privileged: true
    ports:
      - "7080:80"
      - "7443:443"
    command: ["walrus", "--enable-authn=false"]
    environment:
      - SERVER_SETTING_LOCAL_ENVIRONMENT_MODE=docker
      # avoid the impact from docker embedded DNS server.
      - K3S_RESOLV_CONF=
    volumes:
      - /var/run/docker.sock.raw:/var/run/docker.sock
