name: CI

on:
  push:
    tags:
      - '*'
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build extension
        run: make build-extension
        env:
          DOCKER_BUILDKIT: 1
          TAG: ${{ github.ref_name }}

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.CI_DOCKERHUB_USERNAME }}
          password: ${{ secrets.CI_DOCKERHUB_PASSWORD }}

      - name: Push extension
        if: ${{ github.event_name != 'pull_request' }}
        run: make push-extension
        env:
          DOCKER_BUILDKIT: 1
          TAG: ${{ github.ref_name }}